rvm:
  - 1.9.3
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - jruby-9.2.4.0
before_install:
  - gem install bundler
script: "bundle exec rake"
bundler_args: "--without repl documentation"
branches:
  only:
    - master
